import os
import django
from customers.apps import CustomersConfig


os.environ.setdefault("DJANGO_SETTINGS_MODULE", "trustin.settings")
django.setup()

from customers.models import Customer, ContactPerson
from branches.models import Branch


customers_data = [
    {
        "sno": 1,
        "customer_code": "TAS_CUS_22-23_0014",
        "company_name": "TTK Kelrala",
        "contact_person": "ASHA",
        "address": "3/21, 3rd Main Rd, Kottur Garden, Kotturpuram, Chennai, Tamil Nadu 600085.",
        "mobile_no": 9567526842,
        "email": "alm@ttkhealthcare.com",
        "date_of_entry": "20-08-2023",
        "entered_by": "ADMIN",
    },
    {
        "sno": 2,
        "customer_code": "TAS_CUS_22-23_0006",
        "company_name": "2ml Industries",
        "contact_person": "MUTHUKUMAR SK",
        "address": "No.62, Station Road, Radha Nagar, Chrompet Madurai",
        "mobile_no": 7200588582,
        "email": "info.keedriver@gmail.com",
        "date_of_entry": "15-05-2023",
        "entered_by": "ADMIN",
    },
    {
        "sno": 3,
        "customer_code": "TAS_CUS_22-23_0005",
        "company_name": "M/s. Saint Gobain",
        "contact_person": "Ms. Aradhana Menon",
        "address": "IIT Madras Research Park No: a FA, Phase - II, C-Block",
        "mobile_no": 9820963339,
        "email": "aradhana.menon@saint-gobain.com",
        "date_of_entry": "28-04-2023",
        "entered_by": "ADMIN",
    },
    {
        "sno": 4,
        "customer_code": "TAS_CUS_0393",
        "company_name": "Vinyoflex Limited",
        "contact_person": "Shri Vinod Khimji Tilva (M.D.)",
        "address": "7QMV+GMP, Kalyan Society, GIDC UdhyogNagar, Bhakti Nagar, Rajkot, Gujarat 360002",
        "mobile_no": "0281 246 0692",
        "email": " Info@vinyoflex",
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 5,
        "customer_code": "TAS_CUS_0392",
        "company_name": "Dolphinpharma",
        "contact_person": "jayesh bhimani",
        "address": "155/6/7 , New Sardar Market (APMC) Commercial Complex , Puna Kumbhariya Road , Surat ? 395010, Gujarat.",
        "mobile_no": 9016134151,
        "email": "info@dolphinpharma.com",
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 6,
        "customer_code": "TAS_CUS_0391",
        "company_name": "APOLO SURGICAL",
        "contact_person": "Rajesh Patel (Director)",
        "address": "APOLO HOUSE' Opp. Mahalaxmi Diamond, Anil Starch Road, Bapunagar, Ahmedabad - 380 024",
        "mobile_no": "79-2274 4984, 98242 15925",
        "email": "info@apolosurgical.com, raj_apolo@yahoo.com",
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 7,
        "customer_code": "TAS_CUS_0390",
        "company_name": "Delux Surgical",
        "contact_person": "Tushar S. Bagul | Managing Director",
        "address": "11, Swami Narayana Complex, Near Samsung Showroom, Below Manekba Hospital, N. H. 8, Rabari Colony Char Rasta, Amraiwadi Highway, Ahmedabad - 382415, Gujarat, India",
        "mobile_no": 8047638653,
        "email": "deluxsurgical@yahoo.in",
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 8,
        "customer_code": "TAS_CUS_0389",
        "company_name": "Dr Goyal Medical Pvt. Ltd.",
        "address": "206,Signature 1, Makarba,  S.G. Highway ,Ahmedabad-380051 India ",
        "mobile_no": 9913447474,
        "email": "goyalmedical@gmail.com export@goyalmedical.com",
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 9,
        "customer_code": "TAS_CUS_0388",
        "company_name": "Neu Micromed International Pvt. Ltd",
        "contact_person": "Hemal Shah (Manager)",
        "address": "901, Aditya Building, Off CG Road, Navrangpura, Ahmedabad - 380009, Gujarat, India",
        "mobile_no": 8046039532,
        "email": "micromedint@gmail.com",
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 10,
        "customer_code": "TAS_CUS_0387",
        "company_name": "Jimit Medico Surgicals Pvt Ltd",
        "address": 'Gokul Residency, JIMIT HOUSE" 16, Ranchhod Nagar, Near Vinzol Crossing, Besides, near Railway Colony, Vatva, Ahmedabad, Gujarat 382445',
        "mobile_no": "8905570200, 9376124950",
        "email": "jimitsurgicals@gmail.com, info@jimitsurgicals.com",
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 11,
        "customer_code": "TAS_CUS_0386",
        "company_name": "Rajsun Innovations LLP",
        "contact_person": "Mr. Sunil Shinde",
        "address": "18, Sadguru Sanidhya, B/s Baroda Expressway, Maninagar, Ahmedabad, Gujarat, India - 382449",
        "mobile_no": "9638793036, 7069660011, 7925850612",
        "email": "rajsun.innovations@gmail.com",
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 12,
        "customer_code": "TAS_CUS_0385",
        "company_name": "Deep cooling products pvt. Ltd.",
        "address": "C-1 / 6230, G.I.D.C.Estate, Road No.62, Sachin, Surat - 394 230. (Gujarat.) India.",
        "mobile_no": "+91 261 3240528",
        "email": "info@deepeecooling.com",
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 13,
        "customer_code": "TAS_CUS_0384",
        "company_name": "YASH CARE LIFESCIENCES",
        "contact_person": "Mr Shashikant Kanodia (Proprietor)",
        "address": "Plot no.4704, Phase IV, G.I.D.C. Vatva, Ahmedabad - 382445, Gujarat, India",
        "mobile_no": 8037303823,
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 14,
        "customer_code": "TAS_CUS_0383",
        "company_name": "Tridhara Surgical",
        "contact_person": "Mr. Brijesh Patel : +91-9662015739, Mr. Dasrathbhai Patel : +91-9426341226, Mr. Chirag Patel : +91-9904767105",
        "address": "13, Amba Estate, Opp. Chhass Kendra, Nr. Hathijan Ring Road, Vatva - Mahemdabad Road, Vinzol, Ahmedabad - 382445.",
        "mobile_no": "079-25841124",
        "email": "tridharasurgical@yahoo.com, info@tridharasurgical.com",
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 15,
        "customer_code": "TAS_CUS_0382",
        "company_name": "Angel Group of Companies",
        "contact_person": "Siraj Wadhwaniya",
        "address": "F-5 'Firdaus' 4th Floor, Khanpur, Ahmedabad - 380 001. Gujarat State, India.",
        "mobile_no": "91 - 72290 95522",
        "email": "angelproducts1@gmail.com",
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 16,
        "customer_code": "TAS_CUS_0381",
        "company_name": "APEX MEDICAL DEVICES",
        "contact_person": "Mr Arpit Patel (Marketing Director)",
        "address": "Plot No - 10/B, Shyam Ujjawal Industrial Estate, Opp. SBI Bank, Phase - 1, G.I.D.C Vatva, Ahmedabad - 382445, Gujarat, India",
        "mobile_no": "91-79-08037400888, 09904151535",
        "email": "apexmedical@live.in",
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 17,
        "customer_code": "TAS_CUS_0380",
        "company_name": "ALPHA THERAPEUTICS PVT. LTD.",
        "contact_person": "MR. HARDIK PATEL",
        "address": "ATPL CORPORATE HOUSE, RAJODA, NR. KANKAVATI HOTEL, AHMEDABAD-382220, GUJARAT, INDIA",
        "mobile_no": "0091-9327514300, 0091-9374073646, 0091-9376809551, 0091-9374073644",
        "email": "atplalpha@gmail.com, hardik@atplworld.com, dhaval@atplworld.com",
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 18,
        "customer_code": "TAS_CUS_0379",
        "company_name": "Mesco Surgical",
        "contact_person": "Mr Bhavin Shah (Proprietor)",
        "address": "4-5, Khodiyar Ware House Estate, Behind Mahalaxmi Mills, Narol-Isanpur Highway, Narol,Ahmedabad - 382405, Gujarat, India",
        "mobile_no": "8037268330, 7984551012",
        "email": "info@mescosurgical.com",
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 19,
        "customer_code": "TAS_CUS_0378",
        "company_name": "VEDICH BIOTECH",
        "contact_person": "JAYESHKUMAR JOSHI ",
        "address": "10 , 3rd Floor , Shashwat Business Park, Near, Aburoad Highway, Bihari Bag, Palanpur, Gujarat 385001, India.",
        "mobile_no": "094270 37388, 070162 24801",
        "email": "vedichbiotech@gmail.com",
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 20,
        "customer_code": "TAS_CUS_0377",
        "company_name": "Angiplast Pvt Ltd",
        "contact_person": "Mr. Ashit Shah",
        "address": "Plot No 4803 , Phase IV , G.I.D.C. , Vatva, Ahmedabad, Gujarat, India 382445",
        "mobile_no": "+91 9099 928 652 / +91 9099 930 560",
        "email": "sales@angiplast.com, marketing@angiplast.com",
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 21,
        "customer_code": "TAS_CUS_0376",
        "company_name": "Vivenza Pharmasol",
        "contact_person": "Hemal Gajjar",
        "address": "F30, Shakti Arcade, Sola, Ahmedabad, Gujarat, Sola, Ahmedabad, Gujarat, India",
        "mobile_no": 9998986025,
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 22,
        "customer_code": "TAS_CUS_0375",
        "company_name": "Wonder mate",
        "contact_person": "Umesh shekhliya",
        "address": "360 shktivijay SoC Nana varachha, Sarthana Jakat Naka, Surat, Gujarat - 395006, India",
        "mobile_no": 8048372156,
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 23,
        "customer_code": "TAS_CUS_0374",
        "company_name": "Black Bird India",
        "contact_person": "Mehul Patel",
        "address": "L/10, DG Point Shopping, Magob, Magob, Surat, Gujarat - 395010, India",
        "mobile_no": 9558966800,
        "email": "blackbirdindia3@gmail.com",
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 24,
        "customer_code": "TAS_CUS_0373",
        "company_name": "ACLIRE PHARMACEUTICAL",
        "contact_person": "Ritesh Vaholiya",
        "address": "420, 4th Floor, Apple Square, Yogi Chowk, Puna, Un, Surat, Gujarat, India",
        "mobile_no": "99047 02071",
        "email": "info@aclirepharmaceutical.com",
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 25,
        "customer_code": "TAS_CUS_0372",
        "company_name": "Health Pharma",
        "contact_person": "Mr. Dhruvit Kalathiya",
        "address": "414 Silverstone Arcade Causeway Road, Causeway Road, Surat, Gujarat - 395004, India",
        "mobile_no": 8460492819,
        "email": "admin@healthpharma.in",
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 26,
        "customer_code": "TAS_CUS_0371",
        "company_name": "Jivan Health Care",
        "contact_person": "JAGDISH SAVALIYA",
        "address": "No. 21 , Puna Plaza , Magob, Un, Surat, Gujarat - 395010, India",
        "mobile_no": 9510033735,
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 27,
        "customer_code": "TAS_CUS_0370",
        "company_name": "SalesGuruz Online",
        "contact_person": "Akshay Gupte",
        "address": "101 / A, Dhananjay Society, Near Akota Stadium, Akota, Akota, Vadodara, Gujarat, India",
        "mobile_no": "8000963933/9712395803",
        "email": "salesco@salesguruz.com",
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 28,
        "customer_code": "TAS_CUS_0369",
        "company_name": "KWOT Healthcare Private Limited",
        "contact_person": "Mr. Gulabray M (Director)",
        "address": "404, Facet Square, Near Navrachna University, Bhayli, Vadodara - 391 410, Bhayli, Vadodara, Gujarat - 391410, India",
        "mobile_no": 9909919447,
        "email": "KWOTHEALTHCARE@GMAIL.COM",
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 29,
        "customer_code": "TAS_CUS_0368",
        "company_name": "Aadhya International",
        "contact_person": "Hiren",
        "address": "24, Om Villa, Opp. Bhagat Nagar, Ved Gurukul Road, Surat, Katargam, Surat, Gujarat - 395004, India",
        "mobile_no": "099044 05395",
        "email": "contact.aadhyainternational@gmail.com",
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 30,
        "customer_code": "TAS_CUS_0367",
        "company_name": "Peeje Enterprise",
        "contact_person": "Mr. Pravin Dhameliya",
        "address": "8, Ganesh Row House, Shyam Dham Mandir, Sarthana Jakatnaka, Varachha, Varachha, Surat, Gujarat - 395006, India",
        "mobile_no": "9712699474 / 916353238353, 9712699474",
        "email": "peejeenterprise@gmail.com",
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 31,
        "customer_code": "TAS_CUS_0366",
        "company_name": "Dinesh Enterprise",
        "contact_person": "Mr. Yogesh Gaikwad",
        "address": "31 Shree Krishna Complex Opp. Bala Hanuman Temple Gandhi Road, Kalupur, Ahmedabad, Gujarat - 382415, India",
        "mobile_no": "+91 9825164979",
        "email": "dinesh.enterprise1982@gmail.com",
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 32,
        "customer_code": "TAS_CUS_0365",
        "company_name": "Meril Headquarters, India",
        "address": "Meril Corporate Office, Near Bilakhia Stadium, Muktanand Marg, Chala, Vapi - 396 191, Gujarat, India.",
        "mobile_no": "91 260 2408 000",
        "email": "askinfo@merillife.com",
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 33,
        "customer_code": "TAS_CUS_0364",
        "company_name": "Medicare Orthopaedic Implants & Instruments",
        "contact_person": "Ajay Gimonkar (Partner)",
        "address": "Laxmanji Ravtaji Compound, Near Jognimata Mandir, Opp, Agrawal Estate, Beside Pumping Station, Mahendikuwa Road, Ahmedabad-380004 Gujarat, India.",
        "mobile_no": "079 256 20 181",
        "email": "info@medicareortho.com, medicareortho@yahoo.com",
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 34,
        "customer_code": "TAS_CUS_0363",
        "company_name": "GRIPORTHO SURGICALS PRIVATE LIMITED",
        "address": "310, Sanket Avenue, Opp Ambe Vidyalaya, Sama - Savli Road, Vadodara - 390024, Gujarat ? India",
        "mobile_no": "+91 90810 88422",
        "landline_no": "+91 ? 265 2711162",
        "email": "info@griportho.com",
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 35,
        "customer_code": "TAS_CUS_0362",
        "company_name": "GLOBAL ORTHOSYS",
        "contact_person": "Plant / Head Office",
        "address": "Plot No.- 130, Golden Green Industrial park, Survey No - 111, Khambha (Shapar) Rajkot - 360311, Gujarat, India",
        "mobile_no": " 98989 40227, 94272 17406",
        "email": "inquiry@globalorthosys.com",
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 36,
        "customer_code": "TAS_CUS_0361",
        "company_name": "Sigma Surgical Private Limited",
        "contact_person": "Mehul Gothi (Manager)",
        "address": "Survey No 1636/1, Ground Floor, Opp Bharat Petroleum, Indore Highway, Gam Kuha, Ahmedabad - 382433, Gujarat, India",
        "mobile_no": 8048983533,
        "email": "lalji.vora@gmail.com",
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 37,
        "customer_code": "TAS_CUS_0360",
        "company_name": "ORTHOTECH INDIA PVT LTD,",
        "address": "Plot No.6, N.H. 48, At Nadavala, Po, Dist, Kewada, Gujarat 396001",
        "mobile_no": "93741-38286, 98241-38286",
        "email": "orthotech@gmail.com",
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 38,
        "customer_code": "TAS_CUS_0359",
        "company_name": "Biomedortho",
        "contact_person": "Rajendra Suvarna | International Marketing Head",
        "address": "Siddharth Annexe 3, A/242, Second Floor, Near National Highway 8, Vemali, Vadodara - 391740, Gujarat, India",
        "mobile_no": 7942542344,
        "email": "info@biomedortho.com",
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 39,
        "customer_code": "TAS_CUS_0358",
        "company_name": "Samay Surgical",
        "contact_person": "Mr. Nikunj Dedaniya (Manager)",
        "address": "Survey No.212, Plot No.6, Parmar Metal Street, NH-8B, Veraval - Shapar - 360024, Dist. Rajkot, Gujarat, India",
        "mobile_no": "7878152154, 9429115008",
        "landline_no": "02827 252154",
        "email": "info@samaysurgical.com, samay_surgical@yahoo.com",
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 40,
        "customer_code": "TAS_CUS_0357",
        "company_name": "Vishal Surgitech Pvt. Ltd.",
        "address": "Nr. Old tall plaza, mayurmarble street, N-H8b, gondal road, kothariya, rajkot- 360022, gujarat. India.",
        "mobile_no": 9099913051,
        "email": "sales@vishalsurgitech.com",
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 41,
        "customer_code": "TAS_CUS_0356",
        "company_name": "Matrix Meditec Pvt Ltd",
        "address": "34 Saket Industrial Estate Moraiya,Sanand, Ahmedabad - 382 213, Gujarat, India, Rajkot, Gujarat, India",
        "mobile_no": "+ 91 9687659157 , +91 79 48903016",
        "email": " sales@matrixmeditec.com",
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 42,
        "customer_code": "TAS_CUS_0355",
        "company_name": "Fine Ortho",
        "contact_person": "Maulik Kanani (Proprietor)",
        "address": "G-608/A, Kishan Gate, GIDC Metoda-360021, Rajkot, Gujarat, India",
        "mobile_no": "94265 88082, 78784 90001, 81604 30172",
        "email": "fineortho@gmail.com",
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 43,
        "customer_code": "TAS_CUS_0354",
        "company_name": "Hardik International Pvt Ltd",
        "address": "Plot No. G-2041/2042/A, G.I.D.C. Lodhika, Kalawad Road, Metoda, Rajkot, Gujarat 360021",
        "mobile_no": "95740 01818",
        "email": " info@hardikinternational.com",
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 44,
        "customer_code": "TAS_CUS_0353",
        "company_name": "HCM ORTHOCARE PVT.LTD",
        "contact_person": "Kiran Panchal",
        "address": "A/1, Setubandh Park, Opp. Bhagwati Vidhyala School, B/H India Colony, Ahmedabad ? 382350, Gujarat, India",
        "mobile_no": 9998490134,
        "email": "info@hcmortho.com",
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 45,
        "customer_code": "TAS_CUS_0352",
        "company_name": "Innovative Ortho Surgicals Private Limited",
        "contact_person": "Alok Jaiswal (Director)",
        "address": "Plot No. 41, Road No. 5, Sardar Estate, Sayaji Park Society, Vadodara - 390019, Gujarat, India",
        "mobile_no": 8046042828,
        "email": "info@iosplortho.com",
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 46,
        "customer_code": "TAS_CUS_0351",
        "company_name": "SHARMA ORTHOPEDIC (INDIA) PVT. LTD.",
        "address": "445/A, G.I.D.C. Estate,Waghodia - 391760, Vadodara, Gujarat, India",
        "mobile_no": "7284003123, 7284003125, 7698881526",
        "email": "info@sharmaortho.com; exports@sharmaortho.com",
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 47,
        "customer_code": "TAS_CUS_0350",
        "company_name": "NRV OrthoTech Pvt. Ltd",
        "contact_person": "Akash Vadalia (Director)",
        "address": "C-506, Signature 2 Business Park, Nr.Sarkhej-Sanand Circle, Off. S.G.Highway, Sarkhej, Ahmedabad ? 382210, Gujarat, INDIA.",
        "mobile_no": "9727519603, 9099937444",
        "email": "Info@nrvortho.com",
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 48,
        "customer_code": "TAS_CUS_0349",
        "company_name": "bondwellortho",
        "contact_person": "Ashok Sisara | Marketing Director",
        "address": "A-44, Aadarsh-2  Industrial Estate,  Near Guru Dwara, B/h. Aashish Cinema,Odhav, Ahmedabad ? 382415 Gujarat ? INDIA",
        "mobile_no": "9825875287 / 7600532353 / 8490816687 / 7922875287",
        "email": "bondwellortho@gmail.com, info@bondwellortho.com",
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 49,
        "customer_code": "TAS_CUS_0348",
        "company_name": "DKSORTHO & Sharma Pharmaceutical Pvt. Ltd.",
        "contact_person": "Mr. Natrajan Chandran",
        "address": "444, G.I.D.C Estate , Waghodia -391 760, Vadodara,Gujarat, India",
        "mobile_no": "+91-9825027792, 9227703191",
        "email": " info@spcpl.com ",
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
    {
        "sno": 50,
        "customer_code": "TAS_CUS_0347",
        "company_name": "UTESHIYA MEDICARE",
        "address": "7F1/7F2 Dashrathbhai Estate, Behind: Sakriba Party Plot, CTM, Ahmedabad -380026",
        "mobile_no": 9687617820,
        "email": "info@uteshiyamedicare.com",
        "date_of_entry": "24-06-2022",
        "entered_by": "ADMIN",
    },
]

branch = Branch.objects.get(pk=1)


for data in customers_data:
    instance = Customer.objects.create(
        branch=branch,
        company_name=data["company_name"],
        customer_address_line1=data["address"],
        email=data["email"] if data.get("email") is not None else "",
    )

    ins = ContactPerson.objects.create(
        customer=instance,
        person_name=data["contact_person"] if data.get("contact_person") else "No Name",
        mobile_number=data["mobile_no"],
        email=data["email"] if data.get("email") is not None else "",
    )


print("Data added to the database.")
