# Generated by Django 4.2.7 on 2023-11-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='is_Analyst',
            new_name='is_analyst',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='country',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(default='karthikthee7@gmail.com', max_length=254, unique=True, verbose_name='e-mail'),
            preserve_default=False,
        ),
    ]
