# Generated by Django 4.2.7 on 2024-01-01 14:19

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('customers', '0001_initial'),
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TRF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trf_code', models.CharField(editable=False, max_length=255)),
                ('date_of_registration', models.DateField(default=django.utils.timezone.now)),
                ('sample_id', models.CharField(max_length=255, null=True)),
                ('sample_name', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('manufactured_by', models.CharField(max_length=255, null=True)),
                ('batch_or_lot_no', models.CharField(max_length=255, null=True)),
                ('manufactured_date', models.DateField(null=True)),
                ('expiry_date', models.DateField(null=True)),
                ('batch_size', models.IntegerField(default=0)),
                ('format_name', models.CharField(max_length=255)),
                ('nabl_logo', models.BooleanField(default=False)),
                ('no_of_samples', models.IntegerField(default=0)),
                ('sample_storage_condition', models.TextField(blank=True, default='')),
                ('sampling_by', models.CharField(choices=[('CUSTOMER', 'Customer'), ('LABORATORY', 'Laboratory')], max_length=50)),
                ('testing_process', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('BATCH_ANALYSIS', 'Batch Analysis'), ('METHOD_DEVELOPMENT', 'Method Development'), ('METHOD_VALIDATION', 'Method Validation'), ('RD_RESEARCH', 'R&D / Research'), ('REGULATORY', 'Regulatory')], max_length=100), size=None)),
                ('sample_disposal_process', models.CharField(choices=[('DISCARD', 'Discard'), ('RETURN', 'Return')], max_length=100)),
                ('report_sent_by', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('COURIER', 'Courier'), ('EMAIL', 'E-mail')], max_length=100), size=None)),
                ('fail_statement_sent', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=100)),
                ('specific_decision_rule', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=100)),
                ('binary_decision_rule', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=100)),
                ('submission_of_documents', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('MSDS', 'MSDS'), ('COA', 'COA'), ('IFU', 'IFU'), ('IF_ANY_OTHER', 'If any other')], max_length=100), size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trf_branch', to='branches.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trf_customer', to='customers.customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trf_product', to='samples.product')),
                ('test_type', models.ManyToManyField(to='samples.testtype')),
            ],
        ),
        migrations.CreateModel(
            name='TestingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_order', models.IntegerField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trf_test', to='samples.testingparameter')),
                ('trf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trf_testing', to='trf.trf')),
            ],
        ),
        migrations.CreateModel(
            name='SampleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_name', models.CharField(max_length=255)),
                ('batch_or_lot_no', models.CharField(max_length=255)),
                ('manufactured_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('batch_size', models.IntegerField()),
                ('received_quantity', models.IntegerField()),
                ('trf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trf_sample_detail', to='trf.trf')),
            ],
        ),
    ]
