# Generated by Django 4.2.7 on 2024-01-01 14:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trf',
            name='format_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trf',
            name='report_sent_by',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('COURIER', 'Courier'), ('EMAIL', 'E-mail')], max_length=100, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='trf',
            name='sample_disposal_process',
            field=models.CharField(choices=[('DISCARD', 'Discard'), ('RETURN', 'Return')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trf',
            name='sampling_by',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('LABORATORY', 'Laboratory')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trf',
            name='submission_of_documents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('MSDS', 'MSDS'), ('COA', 'COA'), ('IFU', 'IFU'), ('IF_ANY_OTHER', 'If any other')], max_length=100, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='trf',
            name='testing_process',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('BATCH_ANALYSIS', 'Batch Analysis'), ('METHOD_DEVELOPMENT', 'Method Development'), ('METHOD_VALIDATION', 'Method Validation'), ('RD_RESEARCH', 'R&D / Research'), ('REGULATORY', 'Regulatory')], max_length=100, null=True), size=None),
        ),
    ]
