# Generated by Django 4.2.7 on 2023-12-07 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
        ('trf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trf',
            name='city',
        ),
        migrations.RemoveField(
            model_name='trf',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='trf',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='trf',
            name='customer_address_line1',
        ),
        migrations.RemoveField(
            model_name='trf',
            name='customer_address_line2',
        ),
        migrations.RemoveField(
            model_name='trf',
            name='email',
        ),
        migrations.RemoveField(
            model_name='trf',
            name='gst_no',
        ),
        migrations.RemoveField(
            model_name='trf',
            name='pincode_no',
        ),
        migrations.RemoveField(
            model_name='trf',
            name='state',
        ),
        migrations.RemoveField(
            model_name='trf',
            name='website',
        ),
        migrations.AlterField(
            model_name='trf',
            name='batch_or_lot_no',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trf',
            name='batch_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trf',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='trf',
            name='manufactured_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trf',
            name='manufactured_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='trf',
            name='no_of_samples',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trf',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trf_product', to='samples.product'),
        ),
        migrations.AlterField(
            model_name='trf',
            name='received_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trf',
            name='sample_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trf',
            name='sample_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trf',
            name='test_method',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trf',
            name='test_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
