# Generated by Django 4.2.7 on 2023-12-07 15:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trf', '0002_remove_trf_city_remove_trf_company_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trf',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trf',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
