# Generated by Django 4.2.7 on 2023-12-14 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trf', '0003_trf_created_at_trf_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampledetail',
            name='trf',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trf_sample_detail', to='trf.trf'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trf',
            name='test_type',
            field=models.CharField(choices=[('BIO', 'Bio'), ('MECHNICAL', 'Mechnical')], default="BIO", max_length=50),
        ),
    ]
