# Generated by Django 4.2.7 on 2024-01-01 15:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trf', '0003_alter_trf_report_sent_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trf',
            name='submission_of_documents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('MSDS', 'MSDS'), ('COA', 'COA'), ('IFU', 'IFU'), ('IF_ANY_OTHER', 'If any other')], max_length=100), null=True, size=None),
        ),
    ]
