# Generated by Django 4.2.7 on 2024-01-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trf', '0004_alter_trf_submission_of_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trf',
            name='binary_decision_rule',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=100, verbose_name='Lab follows binary decision rule of sample accepance (w=0) do you accept?'),
        ),
        migrations.AlterField(
            model_name='trf',
            name='fail_statement_sent',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=100, verbose_name='Conformity(Passes/ Fail)statement required'),
        ),
        migrations.AlterField(
            model_name='trf',
            name='specific_decision_rule',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=100, verbose_name='Do you need any specific decision rule to be followed by the laboratory?'),
        ),
    ]
