# Generated by Django 4.2.7 on 2024-01-11 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trf', '0005_alter_trf_binary_decision_rule_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SampleDetail',
        ),
    ]
