# Generated by Django 4.2.7 on 2023-11-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_address', models.TextField(blank=True, default='')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('website', models.URLField()),
                ('contact_person_name', models.CharField(max_length=255)),
                ('contact_person_designation', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=19)),
                ('customer_pan_number', models.CharField(max_length=20)),
                ('customer_gst_number', models.CharField(max_length=20)),
                ('nature_of_business', models.CharField(max_length=255)),
                ('product_details', models.CharField(max_length=255)),
                ('market', models.CharField(max_length=255)),
                ('regulatory', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
