# Generated by Django 4.2.7 on 2024-01-01 14:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('accounts', '0001_initial'),
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=255)),
                ('company_id', models.CharField(editable=False, max_length=255)),
                ('customer_address_line1', models.CharField(blank=True, default='', max_length=255)),
                ('customer_address_line2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode_no', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('nature_of_business', models.CharField(max_length=255)),
                ('product_details', models.CharField(max_length=255)),
                ('market', models.CharField(max_length=255)),
                ('regulatory', models.CharField(max_length=255)),
                ('pan', models.CharField(blank=True, max_length=50, null=True)),
                ('gst', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_branch', to='branches.branch')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketing_status', models.CharField(choices=[('', ''), ('MAIL_SENT', 'Mail Sent'), ('ENQUIRES_RECEIVED', 'Enquires Received'), ('QUOTE_SENT', 'Quote Sent'), ('MARKETINT_PLAN', 'Marketint Plan'), ('SITE_VISITED', 'Site Visited'), ('LAB_VISIT_PLAN', 'Lab Visit Plan'), ('LAB_VISITED', 'Lab Visited'), ('FOLLOWUP', 'Followup'), ('WON', 'Won'), ('WIP', 'Work in Progress'), ('HOLD', 'Hold'), ('LOST', 'Lost'), ('SAMPLE_RECEIVED', 'Sample Received')], max_length=30)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True, default='')),
                ('assign_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='follow_assign', to='accounts.hod')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_customer', to='customers.customer')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cus_follow_sample', to='samples.product')),
            ],
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=100)),
                ('landline_number', models.CharField(blank=True, max_length=19, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_detail', to='customers.customer')),
            ],
        ),
    ]
