# Generated by Django 4.2.7 on 2023-11-20 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='contact_person_designation',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='contact_person_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_gst_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_pan_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_address_line1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_address_line2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='gst',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='pan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=19)),
                ('landline_number', models.CharField(blank=True, max_length=19, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_detail', to='customers.customer')),
            ],
        ),
    ]
