# Generated by Django 4.2.7 on 2024-01-11 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_marketing_remove_myuser_is_analyst_and_more'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfollowup',
            name='assign_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='follow_assign', to='accounts.marketing'),
        ),
    ]
