# Generated by Django 4.2.7 on 2024-01-01 14:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('samples', '0001_initial'),
        ('trf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_recived', models.DateField(default=django.utils.timezone.now)),
                ('received_quantity', models.IntegerField(default=0)),
                ('expectation_delivery_date', models.DateField(default=django.utils.timezone.now)),
                ('sample_condition', models.CharField(choices=[('GOOD', 'Good'), ('BAD', 'Bad')], max_length=50)),
                ('sample_quantity', models.CharField(choices=[('SUFFICIENT', 'Sufficient'), ('NEED_MORE', 'Need More')], max_length=50)),
                ('mode_of_recived', models.CharField(choices=[('COURIER', 'Courier'), ('INPERSON', 'Inperson')], max_length=50)),
                ('received_by', models.CharField(max_length=255)),
                ('reviewed_and_approved', models.CharField(max_length=255)),
                ('test_parameters_under_NABL_scope', models.CharField(choices=[('YES', 'Yes'), ('PARTIAL', 'Partial'), ('NO', 'No'), ('NA', 'NA')], max_length=20)),
                ('test_parameters_under_CDSCO', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('NA', 'NA')], max_length=20)),
                ('trf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_trf', to='trf.trf')),
            ],
        ),
        migrations.CreateModel(
            name='AssignHOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hod', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assign_hod', to='accounts.hod')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assign_registration', to='registrations.registration')),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assign_test_type', to='samples.testtype')),
            ],
        ),
    ]
