# Generated by Django 4.2.7 on 2024-01-11 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_name', models.CharField(max_length=255)),
                ('batch_or_lot_no', models.CharField(max_length=255)),
                ('manufactured_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('batch_size', models.IntegerField()),
                ('received_quantity', models.IntegerField()),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_sample', to='registrations.registration')),
            ],
        ),
        migrations.DeleteModel(
            name='AssignHOD',
        ),
    ]
