# Generated by Django 4.2.7 on 2023-11-21 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SampleRequest',
        ),
    ]
