# Generated by Django 4.2.7 on 2023-12-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testingparameter',
            name='test_type',
            field=models.CharField(choices=[('BIO', 'Bio'), ('MECHNICAL', 'Mechnical')], max_length=50),
        ),
    ]
